### ISSUE TITLE
$adobeSign->createAgreement() results in INVALID_LIBRARYDOCUMENT_ID

### ISSUE THREAD

**Issue by searl08** [kevinem/adobe-sign-php#11]
Hi,

I'm wading through getting your .php library working and have run into the following, after creating a transient_document. I see the returned transient_document_id and pass this id to $adobeSign->createAgreement as the libraryDocumentId. The result of $adobeSign->createAgreement() is Fatal error: Uncaught exception 'KevinEm\AdobeSign\Exceptions\AdobeSignException' with message 'INVALID_LIBRARYDOCUMENT_ID:
My Code:

            $file_contents=file_get_contents($file_path);

		$file_stream = GuzzleHttp\Psr7\FnStream::decorate(GuzzleHttp\Psr7\stream_for($file_contents),       [
			'getMetadata' => function() use ($file_path) {
				return $file_path;
			}
		]);		
		$multipart_stream   = new GuzzleHttp\Psr7\MultipartStream([
			[
				'name'     => 'File',
				'contents' => $file_stream
			]
		]);
		
		$transient_document = $adobeSign->uploadTransientDocument($multipart_stream);	
	
		$transient_document_id=$transient_document['transientDocumentId'];

		$adobeSign->createAgreement([
			'documentCreationInfo' => [
				'fileInfos'         => [
					'libraryDocumentId' => $transient_document_id
				],
				'name'              => 'Unsigned Lease',
				'signatureType'     => 'ESIGN',
				'recipientSetInfos' => [
					'recipientSetMemberInfos' => [
						'email' => 'testuser@gmail.com'
					],
					'recipientSetRole' => ['SIGNER']
				],
				'mergeFieldInfo'    => [
					[
						'fieldName'    => 'Name',
						'defaultValue' => 'Test User'
					]
				],
				'signatureFlow'     => 'SENDER_SIGNATURE_NOT_REQUIRED'
			]
		]);

It looks like the returned transient_document_id is 377 characters long. Could this be an issue on my server ?
I noted in Adobe Sign Docs:
**Developer Implementation Notes**

Some API endpoints return identifiers or URLs that can be used in subsequent calls. While the API does not specify how long these identifiers or URLs can be, in practice developers should design their applications to handle up to 2083 characters for URLs and 512 characters for the identifiers.

Any help would be appreciated.
Thanks

**Comment by jb-dev0** [comment]
Check your fileInfos.
You use a transientDocument but give it a libraryDocument.

The fileinfos should look like this:
`'fileInfos'         => [
				'transientDocumentId' => $transient_document_id
			],`
